:sourcesdir: ../../../source

[[rest_api_v2_ex_update_entity]]
=== Изменение существующего экземпляра сущности

Для изменения экземпляра сущности `sales_Order` необходимо выполнить *PUT* запрос по адресу:

`\http://localhost:8080/app/rest/v2/entities/sales_Order/050af491-16ad-7b4d-8499-4d0bace23bb1`

Последняя часть запроса здесь - это идентификатор изменяемой сущности.

OAuth-токен должен быть передан в заголовке запроса `Authorization` с типом *Bearer*.

В теле запроса необходимо передать JSON объект, содержащий только поля, которые мы хотим изменить, например:

[source, json]
----
include::{sourcesdir}/rest-update-order-request.json[]
----

Тело ответа будет содержать три поля:

[source, json]
----
include::{sourcesdir}/rest-update-order-response.json[]
----

Если в ответе необходимо отобразить дополнительные поля, тогда в запрос нужно добавить параметр `responseView` и указать одно из представлений. Например, для запроса с представлением `order-edit`

`\http://localhost:8080/app/rest/v2/entities/sales_Order/050af491-16ad-7b4d-8499-4d0bace23bb1?responseView=order-edit`

ответ будет выглядеть следующим образом:

[source, json]
----
include::{sourcesdir}/rest-update-order-response-view.json[]
----

Возможность указать параметр `responseView` задается с помощью свойства <<cuba.rest.responseViewEnabled,cuba.rest.responseViewEnabled>>, значение по умолчанию `true`. При отключенном свойстве в ответе возвращается полный граф измененной сущности. 

Например, если `cuba.rest.responseViewEnabled` установлено в `false`, то ответ будет выглядеть следующим образом:

[source, json]
----
include::{sourcesdir}/rest-update-order-response-view-disabled.json[]
----

[TIP]
====
JSON объект из примера выше содержит атрибут `version`, это означает, что сущность `sales_Order` реализует интерфейс {manual}/entity_attr_annotations.html#version_annotation[Versioned] и, таким образом, поддерживает оптимистичную блокировку. Чтобы включить оптимистичную блокировку сущностей, установите свойство приложения <<cuba.rest.optimisticLockingEnabled,cuba.rest.optimisticLockingEnabled>> в `true`. Обратите внимание, что если  атрибут `version` не содержится в JSON, оптимистичная блокировка работать не будет.
====